### ISSUE TITLE
license unclear

### ISSUE THREAD

**Issue by hramrach** [geoffmeyers/interceptty#3]
The only file that has a license statement is bsd-openpty.c which claims BSD license.
To fulfill the letter of the license the copyright and license statement should be replicated in a piece of documentation (such as the COPYING file) which is likely to get distributed with binaries.

The interceptty files themselves do not have any license statement whatsoever. Including the GPL license as COPYING file might imply the intent to license under GPL. To properly do so you need to include a license statement as described in the COPYING file at the end. If you are dissatisfied with the verbosity of the statement maybe look at SPDX license identifiers and their use for license statement.

**Comment by geoffmeyers** [comment]
> Copyright 2000-2004 by Scott Gifford sgifford@suspectclass.com This software is licensed under the GNU Public License. See the file COPYING included with this distribution for details

Just to be clear, I did not write this code.  I merely added an archive of it so I could find it again since the original hosting location was awful.  Because of this, I will not go through and add a license to each file as I do not know the origins and/or original licenses.  You are more than welcome to modify your local copy.

**Comment by hramrach** [comment]
Does the original hosting still exist?

The original developer appears to have a github account but is not hosting intecepttty there.

**Comment by geoffmeyers** [comment]
I have no idea.  The timestamps suggest I "mirrored" this 6 years ago.  It's preserved here, but I'm not really supporting it (or even using it).

**Comment by hramrach** [comment]
OK, thanks for the answers
